package uz.xia.taxigo.common

object NetworkErrorCodes {

    const val GLOBAL_ERROR_UNAUTHORIZED_CODE = 20401
    const val GLOBAL_ERROR_GO_TO_IDENTIFICATION_CODE = 407
    const val GLOBAL_ERROR_NEW_OFFER_CODE = 409
    const val GLOBAL_ERROR_DEVICE_LOCKED_CODE = 418
    const val GLOBAL_ERROR_DEVICE_NOT_REGISTERED_CODE = 423
    const val GLOBAL_ERROR_UPDATE_APP_CODE = 426
    const val GLOBAL_ERROR_DEVICE_IS_ROOTED_CODE = 451
    const val GLOBAL_ERROR_OPEN_WEB_SITE_CODE = 503
    const val GLOBAL_ERROR_SERVER_ERROR_CODE = 502
    const val GLOBAL_ERROR_GATEWAY_TIMEOUT_CODE = 504

    const val LOCAL_ERROR_JSON_SYNTAX_EXCEPTION_CODE = 1
    const val LOCAL_ERROR_JSON_EXCEPTION_CODE = 2
    const val LOCAL_ERROR_NULL_POINTER_EXCEPTION_CODE = 3
    const val LOCAL_ERROR_HTTP_EXCEPTION_CODE = 4
    const val LOCAL_ERROR_MALFORMED_JSON_EXCEPTION_CODE = 5
    const val LOCAL_ERROR_UNKNOWN_HOST_EXCEPTION_CODE = 6
    const val LOCAL_ERROR_IO_EXCEPTION_CODE = 7
    const val LOCAL_ERROR_SSL_HANDSHAKE_EXCEPTION_CODE = 8
    const val LOCAL_ERROR_SSL_EXCEPTION_CODE = 9
    const val LOCAL_ERROR_SOCKET_EXCEPTION_CODE = 10
    const val LOCAL_ERROR_SOCKET_TIMEOUT_EXCEPTION_CODE = 11
    const val LOCAL_ERROR_KOTLIN_NULL_POINTER_EXCEPTION_CODE = 12
    const val LOCAL_ERROR_UNKNOWN_EXCEPTION_CODE = 13

    val globalErrors = arrayListOf(
        GLOBAL_ERROR_UNAUTHORIZED_CODE,
        GLOBAL_ERROR_GO_TO_IDENTIFICATION_CODE,
        GLOBAL_ERROR_NEW_OFFER_CODE,
        GLOBAL_ERROR_DEVICE_LOCKED_CODE,
        GLOBAL_ERROR_DEVICE_NOT_REGISTERED_CODE,
        GLOBAL_ERROR_UPDATE_APP_CODE,
        GLOBAL_ERROR_DEVICE_IS_ROOTED_CODE,
        GLOBAL_ERROR_OPEN_WEB_SITE_CODE,
        GLOBAL_ERROR_SERVER_ERROR_CODE,
        GLOBAL_ERROR_GATEWAY_TIMEOUT_CODE
    )

    val localErrors = arrayListOf(
        LOCAL_ERROR_JSON_SYNTAX_EXCEPTION_CODE,
        LOCAL_ERROR_JSON_EXCEPTION_CODE,
        LOCAL_ERROR_NULL_POINTER_EXCEPTION_CODE,
        LOCAL_ERROR_HTTP_EXCEPTION_CODE,
        LOCAL_ERROR_MALFORMED_JSON_EXCEPTION_CODE,
        LOCAL_ERROR_UNKNOWN_HOST_EXCEPTION_CODE,
        LOCAL_ERROR_IO_EXCEPTION_CODE,
        LOCAL_ERROR_SSL_HANDSHAKE_EXCEPTION_CODE,
        LOCAL_ERROR_SSL_EXCEPTION_CODE,
        LOCAL_ERROR_SOCKET_EXCEPTION_CODE,
        LOCAL_ERROR_SOCKET_TIMEOUT_EXCEPTION_CODE,
        LOCAL_ERROR_KOTLIN_NULL_POINTER_EXCEPTION_CODE,
        LOCAL_ERROR_UNKNOWN_EXCEPTION_CODE
    )
}
